Init.
drevops/behat-screenshot pull request #94
Opened 2024-03-11 03:51 UTC by tannguyen04

## Checklist before requesting a review

- [ ] I have formatted the subject to include ticket number as `[#123] Verb in past tense with dot at the end.`
- [ ] I have added a link to the issue tracker
- [ ] I have provided information in `Changed` section about WHY something was done if this was not a normal implementation
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run new and existing relevant tests locally with my changes, and they passed
- [ ] I have provided screenshots, where applicable

## Changed

1.

## Screenshots

2024-03-11 14:16 UTC, tannguyen04 commented
Hi @AlexSkrypnyk 
I have few notes

1. With url token replacements, I am using url encode to build the token replacement. I can not find the way to follow your logic with url tokens.
2. Step name token should not lower cased because some case is sensitive. Ex: https://github.com/drevops/behat-screenshot/pull/94/files#diff-88ecc745a3641e37dcc57852c6bde91b4a709b0d10026876da436f918feb687dR68

2024-03-11 19:54 UTC, AlexSkrypnyk commented on src/DrevOps/BehatScreenshotExtension/Context/ScreenshotContext.php
> +        return $this->replaceToken($filename, ['ext' => $ext]);
@tannguyen04 
Please extract all tones in to `Tokenizer` class.

2024-03-11 19:56 UTC, AlexSkrypnyk requested changes
@tannguyen04 
Could you please:
1. Extract all token-related functionality in to `Tokenizer` class.
2. Add unit tests for Tokeniser class.

2024-03-12 15:19 UTC, tannguyen04 commented
> @tannguyen04 Could you please:
> 
> 1. Extract all token-related functionality in to `Tokenizer` class.
> 2. Add unit tests for Tokeniser class.

Hi @AlexSkrypnyk 

I have done 1 & 2. But phpunit does not pick my test. And it reach over 16hours.
Can you please look into that ?
Thanks.

2024-03-12 18:01 UTC, AlexSkrypnyk requested changes
Please see my inline comments. The Tokenizer class implementation is not correct.

2024-03-13 20:34 UTC, AlexSkrypnyk commented on src/DrevOps/BehatScreenshotExtension/Context/ScreenshotContext.php
> +            'step_name' => $step->getText(),
😗👌

2024-03-13 20:47 UTC, merged

2024-03-14 19:58 UTC, xurizaemon commented
Great work @tannguyen04! 🎈